language: python

matrix:
  fast_finish: true
  include:
    - python: 3.6
      dist: trusty
      env: TOXENV=py36 NO_TESTS_OVER_WIRE=1
      sudo: false
    - python: 3.7
      dist: xenial
      env: TOXENV=py37 NO_TESTS_OVER_WIRE=1
      sudo: true

install:
  - python -mpip install tox
script:
  - tox
after_success:
  - tox -e coveralls
